version: 2.1

commands:
    run-script:
        description: Runs a script from within the current folder
        parameters:
            script:
                type: string
            script-name:
                type: string
        steps:
            - run:
                name: << parameters.script >>
                command: |
                    chmod +x << parameters.script-name >>
                    source << parameters.script-name >>
    install-package:
        parameters:
            package-name:
                type: string
        steps:
            - run:
                command: |
                    apk add << parameters.package-name >> --quiet
jobs:
  build:
    docker:
        - image: alpine:3.7
    steps:
        - checkout
        - install-package:
            package-name: jq
        - run-script:
            script: Run bash script
            script-name: first_bash_script.sh